services:
  web:
    image: docker.cloudsmith.io/dbp-test/webhook-test-app/webhooks-test-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST_ENV: test_env

x-uffizzi:
  ingress:
    service: web
    port: 80
  continuous_preview:
    share_to_github: true
    delete_preview_after: 1h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
