services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    entrypoint: /usr/sbin/nginx-debug
    command: 
      - "-g"
      - "daemon off;"
    configs:
      - source: my_config_2
        target: /etc/nginx/conf.d/default.conf

  worker:
    image: uffizzitest/worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizzitest/vote:latest


  result:
    image: uffizzitest/result:latest

configs:
  my_config_2:
    file: ./config2/vote2.conf


x-uffizzi-ingress:
  service: nginx
  port: 8080
