services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    entrypoint: /usr/sbin/nginx-debug
    command: 
      - "-g"
      - "daemon off;"

  worker:
    image: uffizzitest/worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizzitest/vote:latest


  result:
    image: uffizzitest/result:latest


x-uffizzi-ingress:
  service: nginx
  port: 8080
